TheCloudTheory/arm-estimator

arm-estimator/Products/AppService/AppServicePlanEstimationCalculation.cs
arm-estimator/Properties/launchSettings.json
arm-estimator/arm-estimator.csproj
arm-estimator/templates/issue-44.json
arm-estimator/templates/issue-45.json

It's going to fix #44 as prices for Logic App Standard SKU are now correctly taking vCPU / Memory usage into account.

Fixed calculation of Standard SKU for Logic Apps

---

arm-estimator/templates/bicep/vm_av2.bicep
arm-estimator/templates/vm_av2.json

@kamil-mrzyglod , Feel free to add comments or suggestions. I have Added Bicep and ARM templates for Azure Virtual Machine Av2 Series.

Added templates for VM Av2 Series

---

arm-estimator-tests/ParametersTests.cs
arm-estimator-tests/arm-estimator-tests.csproj
arm-estimator-tests/templates/106-file-and-inline-params.parameters.json
arm-estimator-tests/templates/bicep/106-file-and-inline-params.bicep
arm-estimator/Products/SQL/SQLEstimationCalculation.cs
arm-estimator/Products/SQL/SQLQueryFilter.cs

Added test for providing both file and inline parameters

---

arm-estimator-tests/Generic_ARM_Tests.cs
arm-estimator/Products/ApplicationGateway/ApplicationGatewayEstimationCalculation.cs

Fixed AppGW estimation due to invalid handling of metrics

---

.github/workflows/estimateFromUrl.yml
arm-estimator-tests/ParametersTests.cs
arm-estimator/Template/TemplateParser.cs

My laptop does not like running full-fat Visual Studio, debugging tests was a nightmare. Hopefully this PR looks ok.
In the meantime, I'll get a DevBox up and running 😅
Closes #106

Allow inline params to supersede file params

---

arm-estimator-tests/Generic_ARM_Tests.cs
arm-estimator-tests/ParametersTests.cs
arm-estimator-tests/arm-estimator-tests.csproj
arm-estimator-tests/templates/bicep/securestring.bicep
arm-estimator/WhatIf/WhatIfProcessor.cs

Better handling of test cases

---

.github/workflows/estimateFromUrl.yml

1. Fixed issue with targeting new tags (choice -> string)
2. Bugfix if templateParams are not provided.

Estimate from URL workflow - version and bugfix

---

README.md
arm-estimator-tests/Bicep/LogAnalyticsTests.cs
arm-estimator-tests/arm-estimator-tests.csproj
arm-estimator-tests/templates/bicep/infer-log-analytics-cost.bicep
arm-estimator-tests/templates/bicep/usagePatterns/loganalytics.bicep
arm-estimator/Products/LogAnalytics/LogAnalyticsEstimationCalculation.cs
arm-estimator/Products/LogAnalytics/LogAnalyticsProperties.cs
arm-estimator/WhatIf/WhatIfProcessor.cs

Infer log analytics cost

---

README.md
arm-estimator-tests/Bicep/AcrTests.cs
arm-estimator-tests/arm-estimator-tests.csproj
arm-estimator-tests/templates/bicep/usagePatterns/acr.bicep
arm-estimator/Products/ContainerRegistry/ContainerRegistryEstimationCalculation.cs

ACR free tier calculation

---

arm-estimator-tests/Bicep/SqlTests.cs
arm-estimator-tests/arm-estimator-tests.csproj
arm-estimator-tests/templates/bicep/usagePatterns/sql.bicep
arm-estimator/Products/SQL/SQLEstimationCalculation.cs

Hybrid Benefit can be now disabled with usage pattern

---

arm-estimator-tests/Bicep/SqlTests.cs
arm-estimator-tests/arm-estimator-tests.csproj
arm-estimator-tests/templates/bicep/sql/sqldatabase-additional-storage.bicep
arm-estimator/Products/SQL/SQLEstimationCalculation.cs
arm-estimator/Products/SQL/SQLQueryFilter.cs

Added usage pattern for SQL Database DTU model

---

arm-estimator-tests/ARM/AksTests.cs
arm-estimator-tests/arm-estimator-tests.csproj
arm-estimator-tests/templates/aks/149-bug.json
arm-estimator-tests/templates/aks/149-bug.parameters.json
arm-estimator/Products/AKS/AKSEstimationCalculation.cs
arm-estimator/Products/AKS/AKSRetailQuery.cs

Fixed AKS calculation bug

---

.github/workflows/estimateFromUrl.yml

Added markdown job summary output, consuming workflows will now get a nice cost summary in their workflow run.

Adding job summary to Reusable Workflow

---

arm-estimator-tests/Bicep/LogAnalyticsTests.cs
arm-estimator-tests/azure-cost-estimator-tests.csproj
arm-estimator-tests/templates/bicep/loganalytics/bug-180.bicep
arm-estimator/Products/LogAnalytics/LogAnalyticsEstimationCalculation.cs
arm-estimator/Products/LogAnalytics/LogAnalyticsProperties.cs

Fixed LA estimation when quota is passed as float

---

README.md
arm-estimator-tests/Bicep/SqlTests.cs
arm-estimator-tests/azure-cost-estimator-tests.csproj
arm-estimator-tests/templates/bicep/sql/sqldatabase-elasticpool.bicep
arm-estimator/Products/SQL/SQLElasticPoolEstimationCalculation.cs
arm-estimator/Products/SQL/SQLElasticPoolQueryFilter.cs
arm-estimator/Products/SQL/SQLElasticPoolRetailQuery.cs
arm-estimator/WhatIf/WhatIfProcessor.cs

Added support for elastic pools in SQL

---

arm-estimator/Compilation/ArmTemplateCompiler.cs
arm-estimator/Compilation/BicepCompiler.cs
arm-estimator/Compilation/ICompiler.cs
arm-estimator/Compilation/TemplateCompiler.cs
arm-estimator/Compilation/TerraformCompiler.cs
arm-estimator/Program.cs
arm-estimator/ResourceManager/CapabilitiesCache.cs
arm-estimator/Template/TemplateParser.cs
arm-estimator/WhatIf/AzureWhatIfHandler.cs
arm-estimator/WhatIf/TerraformTemplateParser.cs
arm-estimator/WhatIf/WhatIfParser.cs
arm-estimator/WhatIf/WhatIfProcessor.cs

Added handling of user-triggered cancellation

---

ace-terraform-parser/parser.go
arm-estimator-tests/Terraform/BasicTests.cs
arm-estimator/Compilation/TemplateCompiler.cs
arm-estimator/Compilation/TerraformCompiler.cs
arm-estimator/EstimateOptions.cs
arm-estimator/EstimateOptionsBinder.cs
arm-estimator/Program.cs

Added possibility to pass TF executable

---

arm-estimator-tests/Bicep/CacheTests.cs
arm-estimator/Caching/AzureStorageCacheHandler.cs
arm-estimator/Caching/CacheHandler.cs
arm-estimator/Caching/ICacheHandler.cs
arm-estimator/Caching/LocalCacheHandler.cs
arm-estimator/EstimateOptions.cs
arm-estimator/EstimateOptionsBinder.cs
arm-estimator/Products/VirtualMachine/VirtualMachineQueryFilter.cs
arm-estimator/Program.cs
arm-estimator/ResourceManager/CapabilitiesCache.cs
arm-estimator/WhatIf/AzureWhatIfHandler.cs
arm-estimator/WhatIf/WhatIfParser.cs
arm-estimator/WhatIf/WhatIfProcessor.cs
arm-estimator/azure-cost-estimator.csproj

Added support for Azure Storage cache

---

arm-estimator-tests/Bicep/SqlTests.cs
arm-estimator/Products/SQL/SQLEstimationCalculation.cs
arm-estimator/Products/SQL/SQLQueryFilter.cs

feat(sql): Added support for Business Critical and Hyperscale

---

ace-tests/ConfigurationTests.cs
ace-tests/azure-cost-estimator-tests.csproj
ace-tests/templates/configuration/configuration.json
ace/Configuration.cs
ace/EstimateOptions.cs
ace/EstimateOptionsBinder.cs
ace/Program.cs

Added possibility to pass configuration file

---

ace-tests/Bicep/VmTests.cs
ace/Configuration.cs
ace/Defaults.cs
ace/EstimateOptions.cs
ace/EstimateOptionsBinder.cs
ace/NewestVersionCheck.cs
ace/Program.cs

Add check for new version of ACE

---

ace-tests/Reworked/AKS/AvailabilitySetTests.cs
ace-tests/azure-cost-estimator-tests.csproj
ace-tests/templates/reworked/aks/availability-set.bicep
ace/Products/AKS/AKSQueryFilter.cs

feat(aks): Added support for Availability Set calculation

---

ace-tests/Reworked/AutomationAccount/AutomationAccountTests.cs
ace-tests/azure-cost-estimator-tests.csproj
ace-tests/templates/reworked/automation-account/automation-account.bicep
ace/Products/Automation/AutomationAccountEstimationCalculation.cs

feat(automation): Added inferring cost for Automation Account

---

ace-tests/Reworked/ParametersTests.cs
ace-tests/azure-cost-estimator-tests.csproj
ace-tests/templates/reworked/automation-account/automation-parameters.bicep
ace-tests/templates/reworked/automation-account/automation-parameters.bicepparam
ace/Compilation/BicepCompiler.cs
ace/Compilation/BicepparamStdoutResult.cs
ace/Program.cs

feat(bicep): Added support for `.bicepparam` files

---

ace-tests/Reworked/VirtualNetwork/VirtualNetworkPeeringTests.cs
ace-tests/azure-cost-estimator-tests.csproj
ace-tests/templates/reworked/virtual-network/peering-1-2.bicep
ace-tests/templates/reworked/virtual-network/peering-1-3.bicep
ace-tests/templates/reworked/virtual-network/peering-2-3.bicep
ace/Output/DefaultOutputFormatter.cs
ace/Output/IOutputFormatter.cs
ace/Output/TableOutputFormatter.cs
ace/Products/VirtualNetwork/PeeringMetadata.cs
ace/Products/VirtualNetwork/PeeringType.cs
ace/Products/VirtualNetwork/VNetProperties.cs
ace/Products/VirtualNetwork/VNetRetailQuery.cs
ace/Products/VirtualNetwork/VNetZones.cs
ace/WhatIf/WhatIfProcessor.cs

Calculating prices for VNET zones peerings

---

ace-tests/Reworked/StaticWebApp/StaticWebAppTests.cs
ace-tests/azure-cost-estimator-tests.csproj
ace-tests/mocked-responses/retail-api/static-web-app/standard.json
ace-tests/templates/reworked/static-web-app/static-web-app-free.bicep
ace-tests/templates/reworked/static-web-app/static-web-app-standard.bicep
ace/Products/ContainerRegistry/ContainerRegistryQueryFilter.cs
ace/Products/StaticWebApp/StaticWebAppEstimationCalculation.cs
ace/Products/StaticWebApp/StaticWebAppQueryFilter.cs
ace/Products/StaticWebApp/StaticWebAppRetailQuery.cs
ace/WhatIf/WhatIfProcessor.cs

feat(estimation): :sparkles: Added support for Static Web Apps

---

ace-tests/Reworked/ParametersTests.cs
ace-tests/Reworked/WhatIfTests.cs
ace-tests/azure-cost-estimator-tests.csproj
ace-tests/mocked-responses/what-if/automation-account.json
ace/Configuration.cs
ace/EstimateOptions.cs
ace/EstimateOptionsBinder.cs
ace/Program.cs
ace/WhatIf/AzureWhatIfHandler.cs

Accepting user generated whatif

---

ace-tests/Reworked/OutputTests.cs
ace/Configuration.cs
ace/Defaults.cs
ace/EstimateOptions.cs
ace/EstimateOptionsBinder.cs
ace/Markdown/GeneratorTemplate.md
ace/Output/HtmlOutputGenerator.cs
ace/Output/MarkdownOutputGenerator.cs
ace/Output/OutputHandler.cs
ace/Program.cs
ace/azure-cost-estimator.csproj

Support for Markdown output

---

ace-tests/Reworked/ConfigurationTests.cs
ace/EstimateOptionsBinder.cs

Displaying which options are actually not null
